# GitHub Actions workflow for publishing to PyPI with a manual trigger
# This workflow builds the package and provides a button to publish to PyPI

name: Publish Python 🐍 package to PyPI

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to PyPI?'
        required: true
        default: 'yes'
        type: choice
        options:
          - 'yes'
          - 'no'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish:
    needs: build
    if: ${{ github.event.inputs.publish == 'yes' }}
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/reloadify/0.1.0/
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
